import React, {PropTypes} from 'react';

export default class InputComponent extends React.Component{

    constructor(props){
        super(props);
        this.state = {
            headerArray:["lmPwId","darkRated-Fire","darkRated-Water","darkRated-Other","darkRated-TE","darkRated-Sev","Storm","darkRated-Theft","darkRated-Flood","darkRated-Wind","darkRated-Quake","darkRated-Surge","darkRated-EQFF"],
            dataArray:[
                    {
                        "lmPwId":"12204697",
                        "darkRatedFire":"2027"
                        ,"darkRatedWater":"198",
                        "darkRatedOther":"338",
                        "darkRatedTE":"141",
                        "darkRatedSev":"1642",
                        "storm":"160",
                        "darkRatedTheft":"274",
                        "darkRatedFlood":"463",
                        "darkRatedWind":"467",
                        "darkRatedQuake":"130",
                        "darkRatedSurge":"222",
                        "darkRatedEQFF":"375",
                        "darkRatedEQSL":"2027",
                        "lightRatedFire":"198",
                        "lightRatedWater":"338",
                        "lightRatedOther":"141",
                        "lightRatedTE":"1642"
                    },
                    {
                        "lmPwId":"12204697",
                        "darkRatedFire":"2027"
                        ,"darkRatedWater":"198",
                        "darkRatedOther":"338",
                        "darkRatedTE":"141",
                        "darkRatedSev":"1642",
                        "storm":"160",
                        "darkRatedTheft":"274",
                        "darkRatedFlood":"463",
                        "darkRatedWind":"467",
                        "darkRatedQuake":"130",
                        "darkRatedSurge":"222",
                        "darkRatedEQFF":"375",
                        "darkRatedEQSL":"2027",
                        "lightRatedFire":"198",
                        "lightRatedWater":"338",
                        "lightRatedOther":"141",
                        "lightRatedTE":"1642"
                    },
                    {
                        "lmPwId":"12204697",
                        "darkRatedFire":"2027"
                        ,"darkRatedWater":"198",
                        "darkRatedOther":"338",
                        "darkRatedTE":"141",
                        "darkRatedSev":"1642",
                        "storm":"160",
                        "darkRatedTheft":"274",
                        "darkRatedFlood":"463",
                        "darkRatedWind":"467",
                        "darkRatedQuake":"130",
                        "darkRatedSurge":"222",
                        "darkRatedEQFF":"375",
                        "darkRatedEQSL":"2027",
                        "lightRatedFire":"198",
                        "lightRatedWater":"338",
                        "lightRatedOther":"141",
                        "lightRatedTE":"1642"
                    },
                    {
                        "lmPwId":"12204697",
                        "darkRatedFire":"2027"
                        ,"darkRatedWater":"198",
                        "darkRatedOther":"338",
                        "darkRatedTE":"141",
                        "darkRatedSev":"1642",
                        "storm":"160",
                        "darkRatedTheft":"274",
                        "darkRatedFlood":"463",
                        "darkRatedWind":"467",
                        "darkRatedQuake":"130",
                        "darkRatedSurge":"222",
                        "darkRatedEQFF":"375",
                        "darkRatedEQSL":"2027",
                        "lightRatedFire":"198",
                        "lightRatedWater":"338",
                        "lightRatedOther":"141",
                        "lightRatedTE":"1642"
                    },
                    {
                        "lmPwId":"12204697",
                        "darkRatedFire":"2027"
                        ,"darkRatedWater":"198",
                        "darkRatedOther":"338",
                        "darkRatedTE":"141",
                        "darkRatedSev":"1642",
                        "storm":"160",
                        "darkRatedTheft":"274",
                        "darkRatedFlood":"463",
                        "darkRatedWind":"467",
                        "darkRatedQuake":"130",
                        "darkRatedSurge":"222",
                        "darkRatedEQFF":"375",
                        "darkRatedEQSL":"2027",
                        "lightRatedFire":"198",
                        "lightRatedWater":"338",
                        "lightRatedOther":"141",
                        "lightRatedTE":"1642"
                    },
                    {
                        "lmPwId":"12204697",
                        "darkRatedFire":"2027"
                        ,"darkRatedWater":"198",
                        "darkRatedOther":"338",
                        "darkRatedTE":"141",
                        "darkRatedSev":"1642",
                        "storm":"160",
                        "darkRatedTheft":"274",
                        "darkRatedFlood":"463",
                        "darkRatedWind":"467",
                        "darkRatedQuake":"130",
                        "darkRatedSurge":"222",
                        "darkRatedEQFF":"375",
                        "darkRatedEQSL":"2027",
                        "lightRatedFire":"198",
                        "lightRatedWater":"338",
                        "lightRatedOther":"141",
                        "lightRatedTE":"1642"
                    },
                    {
                        "lmPwId":"12204697",
                        "darkRatedFire":"2027"
                        ,"darkRatedWater":"198",
                        "darkRatedOther":"338",
                        "darkRatedTE":"141",
                        "darkRatedSev":"1642",
                        "storm":"160",
                        "darkRatedTheft":"274",
                        "darkRatedFlood":"463",
                        "darkRatedWind":"467",
                        "darkRatedQuake":"130",
                        "darkRatedSurge":"222",
                        "darkRatedEQFF":"375",
                        "darkRatedEQSL":"2027",
                        "lightRatedFire":"198",
                        "lightRatedWater":"338",
                        "lightRatedOther":"141",
                        "lightRatedTE":"1642"
                    },
                    {
                        "lmPwId":"12204697",
                        "darkRatedFire":"2027"
                        ,"darkRatedWater":"198",
                        "darkRatedOther":"338",
                        "darkRatedTE":"141",
                        "darkRatedSev":"1642",
                        "storm":"160",
                        "darkRatedTheft":"274",
                        "darkRatedFlood":"463",
                        "darkRatedWind":"467",
                        "darkRatedQuake":"130",
                        "darkRatedSurge":"222",
                        "darkRatedEQFF":"375",
                        "darkRatedEQSL":"2027",
                        "lightRatedFire":"198",
                        "lightRatedWater":"338",
                        "lightRatedOther":"141",
                        "lightRatedTE":"1642"
                    },
                    {
                        "lmPwId":"12204697",
                        "darkRatedFire":"2027"
                        ,"darkRatedWater":"198",
                        "darkRatedOther":"338",
                        "darkRatedTE":"141",
                        "darkRatedSev":"1642",
                        "storm":"160",
                        "darkRatedTheft":"274",
                        "darkRatedFlood":"463",
                        "darkRatedWind":"467",
                        "darkRatedQuake":"130",
                        "darkRatedSurge":"222",
                        "darkRatedEQFF":"375",
                        "darkRatedEQSL":"2027",
                        "lightRatedFire":"198",
                        "lightRatedWater":"338",
                        "lightRatedOther":"141",
                        "lightRatedTE":"1642"
                    },{
                        "lmPwId":"12204697",
                        "darkRatedFire":"2027"
                        ,"darkRatedWater":"198",
                        "darkRatedOther":"338",
                        "darkRatedTE":"141",
                        "darkRatedSev":"1642",
                        "storm":"160",
                        "darkRatedTheft":"274",
                        "darkRatedFlood":"463",
                        "darkRatedWind":"467",
                        "darkRatedQuake":"130",
                        "darkRatedSurge":"222",
                        "darkRatedEQFF":"375",
                        "darkRatedEQSL":"2027",
                        "lightRatedFire":"198",
                        "lightRatedWater":"338",
                        "lightRatedOther":"141",
                        "lightRatedTE":"1642"
                    }
            ]
            
        }
    }

    render(){
        return(
            <div className="row" style={{paddingTop:'30px',marginLeft:'0px',marginRight:'0px'}}>
                <div className="col-sm-12">
                    <div className="panel panel-default" style={{textAlign:'center'}}><h3>{this.props.title}</h3></div>
                </div>
                <table className="table table-striped table-bordered">
                        <thead>
                            <tr>
                                {this.state.headerArray.map((item, idx) => (
                                        <th>{item}</th>
                                ))}
                            </tr>
                        </thead>
                        <tbody>
                        {this.state.dataArray.map((item, idx) => (
                                <tr>
                                    <td>{item.lmPwId}</td>
                                    <td>{item.darkRatedFire}</td>
                                    <td>{item.darkRatedWater}</td>
                                    <td>{item.darkRatedOther}</td>
                                    <td>{item.darkRatedTE}</td>
                                    <td>{item.darkRatedSev}</td>
                                    <td>{item.storm}</td>
                                    <td>{item.darkRatedTheft}</td>
                                    <td>{item.darkRatedFlood}</td>
                                    <td>{item.darkRatedWind}</td>
                                    <td>{item.darkRatedQuake}</td>
                                    <td>{item.darkRatedSurge}</td>
                                    <td>{item.darkRatedEQFF}</td>
                                    
                                </tr>
                            ))}
                        </tbody>
                </table>
            </div>    
        )
    }

}