import React, {PropTypes} from 'react';

export default class LightComponent extends React.Component{

    constructor(props){
        super(props);
        this.state = {
            headerArray:["lmPwId","Fire","Water","Other","TE","Sev","Storm","Theft","Flood","Wind","Quake","Surge","EQFF","EQSL"],
            dataArray:[
                    {
                        "lmPwId":"12204697",
                        "Fire":"2027",
                        "Water":"198",
                        "Other":"338",
                        "TE":"141",
                        "Sev":"1141",
                        "Storm":"159",
                        "Theft":"274",
                        "Flood":"463",
                        "Wind":"467",
                        "Quake":"130",
                        "Surge":"222",
                        "EQFF":"222",
                        "EQSL":"222"
                    },
                    {
                        "lmPwId":"12204697",
                        "Fire":"2027",
                        "Water":"198",
                        "Other":"338",
                        "TE":"141",
                        "Sev":"1141",
                        "Storm":"159",
                        "Theft":"274",
                        "Flood":"463",
                        "Wind":"467",
                        "Quake":"130",
                        "Surge":"222",
                        "EQFF":"222",
                        "EQSL":"222"
                    },
                    {
                        "lmPwId":"12204697",
                        "Fire":"2027",
                        "Water":"198",
                        "Other":"338",
                        "TE":"141",
                        "Sev":"1141",
                        "Storm":"159",
                        "Theft":"274",
                        "Flood":"463",
                        "Wind":"467",
                        "Quake":"130",
                        "Surge":"222",
                        "EQFF":"222",
                        "EQSL":"222"
                    },
                    {
                        "lmPwId":"12204697",
                        "Fire":"2027",
                        "Water":"198",
                        "Other":"338",
                        "TE":"141",
                        "Sev":"1141",
                        "Storm":"159",
                        "Theft":"274",
                        "Flood":"463",
                        "Wind":"467",
                        "Quake":"130",
                        "Surge":"222",
                        "EQFF":"222",
                        "EQSL":"222"
                    },
                    {
                        "lmPwId":"12204697",
                        "Fire":"2027",
                        "Water":"198",
                        "Other":"338",
                        "TE":"141",
                        "Sev":"1141",
                        "Storm":"159",
                        "Theft":"274",
                        "Flood":"463",
                        "Wind":"467",
                        "Quake":"130",
                        "Surge":"222",
                        "EQFF":"222",
                        "EQSL":"222"
                    },
                    {
                        "lmPwId":"12204697",
                        "Fire":"2027",
                        "Water":"198",
                        "Other":"338",
                        "TE":"141",
                        "Sev":"1141",
                        "Storm":"159",
                        "Theft":"274",
                        "Flood":"463",
                        "Wind":"467",
                        "Quake":"130",
                        "Surge":"222",
                        "EQFF":"222",
                        "EQSL":"222"
                    },
                    {
                        "lmPwId":"12204697",
                        "Fire":"2027",
                        "Water":"198",
                        "Other":"338",
                        "TE":"141",
                        "Sev":"1141",
                        "Storm":"159",
                        "Theft":"274",
                        "Flood":"463",
                        "Wind":"467",
                        "Quake":"130",
                        "Surge":"222",
                        "EQFF":"222",
                        "EQSL":"222"
                    },
                    {
                        "lmPwId":"12204697",
                        "Fire":"2027",
                        "Water":"198",
                        "Other":"338",
                        "TE":"141",
                        "Sev":"1141",
                        "Storm":"159",
                        "Theft":"274",
                        "Flood":"463",
                        "Wind":"467",
                        "Quake":"130",
                        "Surge":"222",
                        "EQFF":"222",
                        "EQSL":"222"
                    },
                    {
                        "lmPwId":"12204697",
                        "Fire":"2027",
                        "Water":"198",
                        "Other":"338",
                        "TE":"141",
                        "Sev":"1141",
                        "Storm":"159",
                        "Theft":"274",
                        "Flood":"463",
                        "Wind":"467",
                        "Quake":"130",
                        "Surge":"222",
                        "EQFF":"222",
                        "EQSL":"222"
                    },
                    {
                        "lmPwId":"12204697",
                        "Fire":"2027",
                        "Water":"198",
                        "Other":"338",
                        "TE":"141",
                        "Sev":"1141",
                        "Storm":"159",
                        "Theft":"274",
                        "Flood":"463",
                        "Wind":"467",
                        "Quake":"130",
                        "Surge":"222",
                        "EQFF":"222",
                        "EQSL":"222"
                    },
                    {
                        "lmPwId":"12204697",
                        "Fire":"2027",
                        "Water":"198",
                        "Other":"338",
                        "TE":"141",
                        "Sev":"1141",
                        "Storm":"159",
                        "Theft":"274",
                        "Flood":"463",
                        "Wind":"467",
                        "Quake":"130",
                        "Surge":"222",
                        "EQFF":"222",
                        "EQSL":"222"
                    }
            ]
            
        }
    }

    render(){
        return(
            <div className="row" style={{paddingTop:'30px',marginLeft:'0px',marginRight:'0px'}}>
                <div className="col-sm-12">
                    <div className="panel panel-default" style={{textAlign:'center'}}><h3>{this.props.title}</h3></div>
                </div>
                <table className="table table-stripped table table-bordered">
                        <thead>
                            <tr>
                                {this.state.headerArray.map((item, idx) => (
                                        <th>{item}</th>
                                ))}
                            </tr>
                        </thead>
                        <tbody>
                        {this.state.dataArray.map((item, idx) => (
                                <tr>
                                    <td>{item.lmPwId}</td>
                                    <td>{item.Fire}</td>
                                    <td>{item.Water}</td>
                                    <td>{item.Other}</td>
                                    <td>{item.TE}</td>
                                    <td>{item.Sev}</td>
                                    <td>{item.storm}</td>
                                    <td>{item.Theft}</td>
                                    <td>{item.Flood}</td>
                                    <td>{item.Wind}</td>
                                    <td>{item.Quake}</td>
                                    <td>{item.Surge}</td>
                                    <td>{item.EQFF}</td>
                                    <td>{item.EQSL}</td>
                                </tr>
                            ))}
                        </tbody>
                </table>
           </div>     
        )
    }

}